services:
  - type: web
    name: psicologia-oscura-proyecto-x
    env: node
    rootDir: backend
    buildCommand: npm install && npm run seed && npm run previews
    startCommand: npm start
    healthCheckPath: /api/health
